CREATE TABLE HOTEL (
  ID      NUMBER,
  CONSTRAINT HOTEL_PK PRIMARY KEY (ID),
  COUNTRY NVARCHAR2(50) DEFAULT 'N/A',
  CONSTRAINT COUNTRY_CHECK CHECK (COUNTRY NOT IN ('ROMANIA', 'BELGIUM', 'CHINA', 'UKRAINE')),
  CITY    NVARCHAR2(50) NOT NULL,
  STREET  CLOB

);