---1 TASK
ALTER TABLE EMPLOYEES
  DROP (REPORTS_TO, NOTES, PHOTO);

--2 TASK
ALTER TABLE PRODUCTS
  DROP CONSTRAINT SUPPLIER_FK;
ALTER TABLE SUPPLIERS
  DROP CONSTRAINT SUPPLIER_PK;
ALTER TABLE SUPPLIERS
  ADD CONSTRAINT PHONE_PK PRIMARY KEY (PHONE);

--3
ALTER TABLE CUSTOMERS
  ADD IS_ACTIVE NUMBER DEFAULT 0 CHECK (IS_ACTIVE = 0 OR IS_ACTIVE = 1) NOT NULL;

--4 HERE WE SAVES PICTURES IN BLOB
ALTER TABLE CATEGORIES
  MODIFY PICTURE NVARCHAR2(100);